### ISSUE TITLE
Week 2 - error in tutorial notebook: Can't register the Allen Cell Types Database neuron morphology

### ISSUE THREAD

**Issue by 0-crypt** [BlueBrain/MOOC-neurons-and-synapses-2017#100]
I'm currently using the notebook: Step by step jupyter notebook for bringing data to Nexus v1.ipynb using google colab which is a tutorial for Week 2.

This line of code returns False, which I assume indicates that registration failed. How do I make it work? I've tried entering fresh token and reinitialized several times but to no avail. Any solutions? Thank you.

Input: 
forge.register(nm_allen_resources)

Output:
<action> _register_one
<succeeded> False
<error> AttributeError: 'NoneType' object has no attribute 'format'

**Comment by jdcourcol** [comment]
@imsdu can someone look into that in the absence of @samuel-kerrien ?

**Comment by 0-crypt** [comment]
There is another issue.  https://sandbox.bluebrainnexus.io is frequently down. :|

**Comment by MFSY** [comment]
Hi @0-crypt ,
This is fixed now. Give it another try
