### ISSUE TITLE
Jupyter notebooks one_cell_minds

### ISSUE THREAD

**Issue by moondog-425** [BlueBrain/MOOC-neurons-and-synapses-2017#101]
When trying to complete the "Configure a forge client to store, manage and access datasets" section, I get the following error message: 
<img width="1190" alt="image" src="https://github.com/BlueBrain/MOOC-neurons-and-synapses-2017/assets/139163812/4a934ed4-f92e-4ee9-884b-6d3c3f3612b8">

I have followed every step as indicated, the only deviation is that I am using python 3.9. What is going on? 

Thank you very much in advance!

**Comment by jdcourcol** [comment]
@MFSY can you look into it ?

**Comment by moondog-425** [comment]
> @MFSY can you look into it ?

I still run int the same issue. 

<img width="1680" alt="image" src="https://github.com/BlueBrain/MOOC-neurons-and-synapses-2017/assets/139163812/85ef45db-b9f9-4bc9-a9df-90f418725ace">

https://bluebrain.github.io/nexus/contexts/resource.json is not resolvable -- 404 error

**Comment by MFSY** [comment]
Hi @moondog-425 ,
We'll come back to you with a fix this week.

**Comment by moondog-425** [comment]
> Hi @moondog-425 , We'll come back to you with a fix this week.

Any updates on this issue? Thank you in advance!

**Comment by MFSY** [comment]
Hi @moondog-425 ,
This error is fixed now. Please try again and let us know in case of an issue.
