### ISSUE TITLE
Week 3 graded assignment invalid key error

### ISSUE THREAD

**Issue by briane412** [BlueBrain/MOOC-neurons-and-synapses-2017#102]
I am attempting to submit the graded assignment for week 3 but when I do I get this error message:
"The key you provided is invalid. Please double-check on the course's site. If the problem persists, contact the organisers of the course." 
I set the key to "a" as per the instructions. Should I be using a different key?
![Edx_Week3_Screenshot](https://github.com/BlueBrain/MOOC-neurons-and-synapses-2017/assets/47408108/ad35edfe-438a-43eb-acec-69aa90e44d47)

**Comment by stefanoantonel** [comment]
Hello Brian,
I'm sorry that you are having this issue. The key should appear on EDX in the same page where you have the link to the notebook. Let me contact the internal team and see why it is not showing up.

We will back to you soon

**Comment by stefanoantonel** [comment]
After talking with the team, we have fixed the issue. There was something that was removed by mistake. We have re-added.

For the graded exercises, you should see a section that contains the Key that you need to use in the Jupyter Notebook as below

<img width="1230" alt="Screenshot 2024-06-04 at 10 02 12" src="https://github.com/BlueBrain/MOOC-neurons-and-synapses-2017/assets/4954312/82cd661d-0096-412b-a922-60f5c6f570df">

Let me know if you have any other question

**Comment by jdcourcol** [comment]
please reopen if the issue is not fixed.

**Comment by briane412** [comment]
@stefanoantonel @jdcourcol I am not seeing the key icon when I login to the website. I'm using chrome if that's relevant. 
![image](https://github.com/BlueBrain/MOOC-neurons-and-synapses-2017/assets/47408108/d092873e-902f-43d6-896d-06d492f481ea)

**Comment by stefanoantonel** [comment]
I have contacted the person in charge to take actions on this. Still I have not heard back from her yet

**Comment by stefanoantonel** [comment]
Hello, you should be able to see the submission key for the graded exercises

**Comment by briane412** [comment]
@stefanoantonel thank you! I was able to see the key this time and have successfully submitted the exercise.
