### ISSUE TITLE
week 3 Modeling neurons failing

### ISSUE THREAD

**Issue by jdcourcol** [BlueBrain/MOOC-neurons-and-synapses-2017#21]
I logged in with a new created user:

in this cell:
![image](https://user-images.githubusercontent.com/5441880/27427587-d05da8fe-573f-11e7-97c6-931e679e0594.png)
I got that call stack:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-26-ea2069647a71> in <module>()
     15     max_voltages.append(max(voltage))
     16 
---> 17 plt.plot(gnabar_range, max_voltages, 'oC0')
     18 plt.xlabel('gnabar (S/cm2)')
     19 plt.ylabel('Maximum AP voltage')

/home/jupyter/.local/lib/python2.7/site-packages/matplotlib/pyplot.pyc in plot(*args, **kwargs)
   3152         ax.hold(hold)
   3153     try:
-> 3154         ret = ax.plot(*args, **kwargs)
   3155     finally:
   3156         ax.hold(washold)

/home/jupyter/.local/lib/python2.7/site-packages/matplotlib/__init__.pyc in inner(ax, *args, **kwargs)
   1810                     warnings.warn(msg % (label_namer, func.__name__),
   1811                                   RuntimeWarning, stacklevel=2)
-> 1812             return func(ax, *args, **kwargs)
   1813         pre_doc = inner.__doc__
   1814         if pre_doc is None:

/home/jupyter/.local/lib/python2.7/site-packages/matplotlib/axes/_axes.pyc in plot(self, *args, **kwargs)
   1422             kwargs['color'] = c
   1423 
-> 1424         for line in self._get_lines(*args, **kwargs):
   1425             self.add_line(line)
   1426             lines.append(line)

/home/jupyter/.local/lib/python2.7/site-packages/matplotlib/axes/_base.pyc in _grab_next_args(self, *args, **kwargs)
    384                 return
    385             if len(remaining) <= 3:
--> 386                 for seg in self._plot_args(remaining, kwargs):
    387                     yield seg
    388                 return

/home/jupyter/.local/lib/python2.7/site-packages/matplotlib/axes/_base.pyc in _plot_args(self, tup, kwargs)
    334         ret = []
    335         if len(tup) > 1 and is_string_like(tup[-1]):
--> 336             linestyle, marker, color = _process_plot_format(tup[-1])
    337             tup = tup[:-1]
    338         elif len(tup) == 3:

/home/jupyter/.local/lib/python2.7/site-packages/matplotlib/axes/_base.pyc in _process_plot_format(fmt)
    114         else:
    115             raise ValueError(
--> 116                 'Unrecognized character %c in format string' % c)
    117 
    118     if linestyle is None and marker is None:

ValueError: Unrecognized character C in format string

**Comment by wvangeit** [comment]
Wow, how did that get there, probably accidental copy-paste, will fix the format string.

**Comment by wvangeit** [comment]
Actually, was not really an error. That's a color in new version of matplotlob. Something is going wrong with pip install

**Comment by jdcourcol** [comment]
be careful because notebook shares python installation and some notebooks are installing matplotlib.

**Comment by wvangeit** [comment]
actually, in my case it works. Did you run this in a notebook with a pip install on top ?

**Comment by jdcourcol** [comment]
I ran it as a newly created user, in the order of the notebooks
