### ISSUE TITLE
import error when using submission widget

### ISSUE THREAD

**Issue by jdcourcol** [BlueBrain/MOOC-neurons-and-synapses-2017#22]
I ran through notebook week 3. Graded exercise as a newly created user:
![image](https://user-images.githubusercontent.com/5441880/27427678-220cfeb6-5740-11e7-8ac9-c4c4608a2632.png)

**Comment by antonelepfl** [comment]
@wvangeit 
If we put the pip install and the import on the very top of the notebook (before !pip install -q bluepyopt==1.5.12 matplotlib==2.0.2 numpy==1.13.0)
And then in the end we just call the widget the error disappears.
Could you change that please?

**Comment by wvangeit** [comment]
ok, interesting .... will have a look

**Comment by wvangeit** [comment]
Do we know 'why' this happens ? 
Not sure we should try to fix it before we know it won't affect other things

**Comment by wvangeit** [comment]
Ok, we figured out why this happens. For future reference, the 'import neuron' statement sets the PYTHONHOME variable, and this messes up the pip / virtualenv in the collab.
To solve this, one should run:

import os
os.unsetenv('PYTHONHOME')

before every pip (or after importing neuron)
