### ISSUE TITLE
Set up your HBP Collab not working

### ISSUE THREAD

**Issue by James-Brown** [BlueBrain/MOOC-neurons-and-synapses-2017#50]
I have tried Many times to set up an HBP account without successes.  I press the button GetHBP Invitation and receive:
An invitation has been sent to your address jim@seti.net.

Go to your inbox and search for an email named Invitation to Collaboratory. Open it and follow the steps.

Once your HBP account has been created, come here to finish setting it up for this course.

But no email ever arrives.
Some systems will not accept that my email address is so short or that it ends in 'Net' but it is correct. I am well aware of the junk folder and the response is not there.

**Comment by alex4200** [comment]
@Annechien Do you know who can take a look at this issue?

**Comment by James-Brown** [comment]
I gave up trying to get the email responder to work. I finally had to create a Google email account, reassociated my edX account to this new one and finally was able to create an HBP account.
Something is dreadfully wrong somewhere.

**Comment by stefanoantonel** [comment]
As the HBP Collab is deprecated. I'll close this
