### ISSUE TITLE
malformed answer on week 4

### ISSUE THREAD

**Issue by jdcourcol** [BlueBrain/MOOC-neurons-and-synapses-2017#51]
Subject: Simulation Neuroscience MOOC Week 4 question
Date: 6 January 2020 at 12:23:42 GMT+2

> 
> Dr. Segev,
> 
> I'm taking the Simulation Neuroscience MOOC on edX. For the graded assignment of week 4, when I try to submit my answer, I get the following message:
> 
> The grading process failed to complete. Please double-check your answer or contact the organizers of the course with the following information: [params: {u'answer': u'{Q1: "0.2880502974240863", "Q2": "0.9486832980505138", "Q3": "3/5", "Q4": "2/5", "Q5": "2.51619269984"}', u'submission_token': u'4fZZmzE018mvTGlKWrtMoVQSDbuL'} , exception: Malformed answer. Expected answer of the form '{"key":value,...}'].

**Comment by stefanoantonel** [comment]
It seems that the `Q1` does not contain the quotes. I'll close this
