### ISSUE TITLE
Cannot open W2 Graded exercise

### ISSUE THREAD

**Issue by aleksandernitka** [BlueBrain/MOOC-neurons-and-synapses-2017#57]
I am unable to run the python notebook on collab. Tried to do it locally but cannot download the submission repo. Please advise.

**Comment by alex4200** [comment]
@aleksandernitka  Can you please report the error you get, and attach possibly a screenshot?

**Comment by aleksandernitka** [comment]
<img width="1666" alt="error" src="https://user-images.githubusercontent.com/19268202/102811880-64e13b00-43c6-11eb-8b6a-7c9f68671487.png">

**Comment by alex4200** [comment]
Please write to support@humanbrainproject.eu and include your screenshot, and your User ID. 

In the meantime, you can try to use a different browser, clean the browser data, or try to use a private browser tab.

**Comment by alobiz-a** [comment]
I had the same error when using Chrome. Try Firefox.

**Comment by samuel-kerrien** [comment]
Dear @aleksandernitka, have you had a chance to hear from HBP with respect to the issue you reported ?

**Comment by aleksandernitka** [comment]
Hi @samuel-kerrien yes I have, still working on other issues I am having with the platform, but this issue can be closed as a system ticker has been raised on HBP platform. Thanks for your help.
