### ISSUE TITLE
Unable to submit graded exercises

### ISSUE THREAD

**Issue by alobiz-a** [BlueBrain/MOOC-neurons-and-synapses-2017#58]
Hi, everytime I try to load the submission widget into Jupyter notebook, I get told that there is no module named single_cell_mooc_client.

Anyone know why this is or how to fix it?

![image](https://user-images.githubusercontent.com/76615392/103170793-093c0500-483f-11eb-8faf-b0beb75c44ac.png)

**Comment by alex4200** [comment]
Hello @alobiz-a, try to rerun the "install" cell, but using the following command:

`!pip install --upgrade --pre -i https://bbpteam.epfl.ch/ repository/devpi/simple/ single-cell-mooc-client`

(so the same command without `-q` and without `> /dev/null`, so you can see if there is an error).

**Comment by alobiz-a** [comment]
@alex4200 Thanks!

I've tried it and I get an error message telling me I have an invalid requirement:
![image](https://user-images.githubusercontent.com/76615392/103583391-874f7a00-4ed7-11eb-9232-4f2b3b3c9176.png)

Any idea what I can do next?

**Comment by alex4200** [comment]
Oh, I seem to have given a somewhat incorrect command. There should be no space before "repository". Try the following corrected command:

`!pip install --upgrade --pre -i https://bbpteam.epfl.ch/repository/devpi/simple/ single-cell-mooc-client`

**Comment by alobiz-a** [comment]
@alex4200 Ah, thank you. This time I get a different error...

![image](https://user-images.githubusercontent.com/76615392/103643934-6a558e00-4f4d-11eb-84ad-225346d8a739.png)

**Comment by alex4200** [comment]
Add the following line to the install cell:

`!pip install --upgrade pip`

just before the other 'pip install' command in order to upgrade pip, and try again.

**Comment by alobiz-a** [comment]
Good stuff!! It finally asks me for a submission key! Thank you!
![image](https://user-images.githubusercontent.com/76615392/103704934-145f0580-4fa2-11eb-989f-2ff4beda3678.png)

**Comment by alobiz-a** [comment]
I just use the respective key provided from the course on edX, right?

**Comment by alex4200** [comment]
Yes, that should work.
