### ISSUE TITLE
Invalid key

### ISSUE THREAD

**Issue by alobiz-a** [BlueBrain/MOOC-neurons-and-synapses-2017#62]
Hi all!

I am trying to submit the week 2 graded exercise, but I get an error message saying the key is invalid.
(I got this key from the Week 2 assignment page on EdX.)

Any ideas on what I can do to get this working?

**Comment by AGuyNextDoor** [comment]
Same here and it doesn't seem to work for any graded exercises for any week. 
I've posted it on the [HBP forum](https://forum.humanbrainproject.eu/t/submission-key-hpb-collab/1516), I'll try keeping you updated if I have an answer there

**Comment by antonelepfl** [comment]
We are looking into this issue

**Comment by antonelepfl** [comment]
As a workaround you can re-install the `single-cell-mooc-client` package version `0.0.6`

```
!pip -q install --upgrade -i https://bbpteam.epfl.ch/repository/devpi/simple/ single-cell-mooc-client==0.0.6
```

You might need to restart the kernel to apply these changes
