### ISSUE TITLE
StochasticTsodyksMarkram_AMPA_NMDA.mod does not compile (in "Week 4. Graded assignment.ipynb")

### ISSUE THREAD

**Issue by Anner-deJong** [BlueBrain/MOOC-neurons-and-synapses-2017#65]
Output when running `!nrnivmodl ./MOOC-neurons-and-synapses-2017/ModelingSynapses/mechanisms` :
```
...
Translating StochasticTsodyksMarkram_AMPA_NMDA.mod into /content/x86_64/StochasticTsodyksMarkram_AMPA_NMDA.c
R not really a STATE; Ie. No differential equation for it.
 at line 281 in file StochasticTsodyksMarkram_AMPA_NMDA.mod
...
 ```

 Tried several changes (see below) but my unfamiliarity with .mod files, as well as I cant compile locally but only in a colab, is not getting me anywhere. Hopefully someone more familiar has a fix.

 -----------
Side notes:

It seems this file is an update from the non Stochastic file, but with some of the updates missing (e.g. the `R`, but also `local A` still declared but unused in `NET_RECEIVE`, `R` never assigned to, ..)

 - making R a local like Psurv, but R state should persist so seems wrong
 - making R a PARAMETER, but gives other compiler errors
 - others

**Comment by wvangeit** [comment]
It looks like something changed in NEURON. Somebody else had reported this before:
https://github.com/BlueBrain/MOOC-neurons-and-synapses-2017/issues/60

I've just pushed a fix to this repo:
https://github.com/BlueBrain/MOOC-neurons-and-synapses-2017/pull/66/files

This fix will only be visible to people who create a new collab, so I propose for now you manually apply the fix above.

Thanks, let us know how it goes.

**Comment by Anner-deJong** [comment]
Compiles like a charm, thank you Werner van Geit!

(Sorry I didnt see the other issue before)
