### ISSUE TITLE
INTERNAL SERVER ERROR (Set up HBP collab error)

### ISSUE THREAD

**Issue by isi1000** [BlueBrain/MOOC-neurons-and-synapses-2017#67]
I can't get the invitation from HBP. When I click the button (in the configuration section in week 2) a window appears with the message "Internal server error". What I can do?

**Comment by antonelepfl** [comment]
Thank you for reporting this, can you send me your email address that you used in EDX?

**Comment by isi1000** [comment]
Isidrosobrinos@gmail.com

**Comment by antonelepfl** [comment]
As a temporal solution so you are not blocked, I have invited you to the Collab

**Comment by stefanoantonel** [comment]
The HBP Collab is deprecated. I'll close this.
