### ISSUE TITLE
Problem with Collab: The page have redirect you so many times

### ISSUE THREAD

**Issue by isi1000** [BlueBrain/MOOC-neurons-and-synapses-2017#68]
Hi! HBP collaboration is not working, when i try to open the workspace it said to me "jupyterhub.humanbrainproject.org have redirect you so many times".
It have already happened to me the last week (trying to do the week2 asiggment), and i could fix it open the collaboratory in firefox but now i've try it in firefox, chrome, microssoft edge and nothing works.

what should i do?
Thanks.

**Comment by stefanoantonel** [comment]
The HBP Collab is deprecated. I'll close this.
