### ISSUE TITLE
Collabs do not work any more

### ISSUE THREAD

**Issue by mlrennerfr** [BlueBrain/MOOC-neurons-and-synapses-2017#70]
Hi! I cannot longer connect to HBP collabs, so I cannot go through the exercises of theSimulation Neuroscience MOOC. Is that me, my account, or is it something else?
Thank you!
Marianne

**Comment by alobiz-a** [comment]
Hey, I seem to have the same issue. I don't know where to go from this page:

![image](https://user-images.githubusercontent.com/76615392/126274699-cb23f37b-9967-4a1c-979c-15a096fce678.png)

**Comment by stefanoantonel** [comment]
I have contacted the support team to have a look.
Can you tell me your userid?

**Comment by alobiz-a** [comment]
Thank you. Here is my userID:  309830. Username: alobiz



Il giorno mar 20 lug 2021 alle ore 08:55 stefanoantonel <
***@***.***> ha scritto:

**Comment by stefanoantonel** [comment]
While we are investigating this issue, if you need to submit your answers, you can just download the notebooks from [MOOC-neurons-and-synapses-2017](https://github.com/BlueBrain/MOOC-neurons-and-synapses-2017) repo.

To check which notebooks correspond to each week, see [weeks_config](https://github.com/BlueBrain/MOOC-neurons-and-synapses-2017/blob/master/weeks_config.json)

For the submission, as the widget might not work outside Collab you can just use simple python code to POST to Edx.

```python

import requests
import json

ENDPOINT = 'https://bbp.epfl.ch/edx-single-cell/answer'

SUBMISSION_KEY = 'EDX_SUBMISSION_KEY'
ANSWERS = 'YOUR_ANSWER'

data = {
  'submission_token': SUBMISSION_KEY,
  'answer': json.dumps(ANSWERS),
}

try:
  response = requests.post(ENDPOINT, json=data, verify=False)
except ValueError:
  print('Error sending the answers')

if response.status_code == requests.codes.ok:
  grade = response.json()['grade']
  print('Your answer was submitted successfully!')
  print('GRADE: {}'.format(grade['value']))
else:
  print(response.json()['message'])
```

**Comment by stefanoantonel** [comment]
HBP Colla is deprecated. I am closing this issue.
