### ISSUE TITLE
NMC portal notebooks issues

### ISSUE THREAD

**Issue by antonelepfl** [BlueBrain/MOOC-neurons-and-synapses-2017#72]
In notebooks:
[Final graded assignment.ipynb](https://github.com/BlueBrain/MOOC-neurons-and-synapses-2017/blob/2021_release/NMCPortal/Final%20graded%20assignment.ipynb)
[NMCPortal.ipynb](https://github.com/BlueBrain/MOOC-neurons-and-synapses-2017/blob/2021_release/NMCPortal/NMCPortal.ipynb)

When:
```
neurom.viewer.draw(neurom.load_neuron('morphology/dend-C310897B-P3_axon-C220498B-P3_cor_-_Clone_1.asc'));
```

Output:
```
/usr/local/lib/python3.8/dist-packages/neurom/view/common.py:108: MatplotlibDeprecationWarning: Passing non-integers as three-element position specification is deprecated since 3.3 and will be removed two minor releases later.
  ax = fig.add_subplot(subplot, **params)
```

To access to NOTO platform [link](https://edge.edx.org/courses/course-v1:EPFLx+SimNeuroX+2017_T2/courseware/94e4883f4598474ca102781bbe5688ef/36386e964bc8495e850c42f266a3f6c9/1?activate_block_id=block-v1%3AEPFLx%2BSimNeuroX%2B2017_T2%2Btype%40vertical%2Bblock%40cf49083f2b9f4e03b1ed8577b22cbfea)

Please commit changes to branch `2021_release`

Do you have an idea of what could be happening? @wvangeit @mgeplf

**Comment by wvangeit** [comment]
@antonelepfl maybe a NeuroM ticket should be created?

**Comment by antonelepfl** [comment]
This issue was fixed by a new release of NeuroM
