### ISSUE TITLE
ConstrModels notebooks issues

### ISSUE THREAD

**Issue by antonelepfl** [BlueBrain/MOOC-neurons-and-synapses-2017#73]
In notebooks:
[GradedExercise.ipynb](https://github.com/BlueBrain/MOOC-neurons-and-synapses-2017/blob/2021_release/ConstrModels/TutBallStickOpt/GradedExercise.ipynb)
[ballandstickopt.ipynb](https://github.com/BlueBrain/MOOC-neurons-and-synapses-2017/blob/2021_release/ConstrModels/TutBallStickOpt/ballandstickopt.ipynb)

With: 
bluepyopt (v 1.10.12) and numpy (1.19.5):

We get some errors / warning such as:
```
New error when importing bluepyopt: RuntimeError Traceback (most recent call last)
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
```
```
MatplotlibDeprecationWarning: Passing non-integers as three-element position specification is deprecated since 3.3 and will be removed two minor releases later.

```

To access to NOTO platform [link](https://edge.edx.org/courses/course-v1:EPFLx+SimNeuroX+2017_T2/courseware/94e4883f4598474ca102781bbe5688ef/36386e964bc8495e850c42f266a3f6c9/1?activate_block_id=block-v1%3AEPFLx%2BSimNeuroX%2B2017_T2%2Btype%40vertical%2Bblock%40cf49083f2b9f4e03b1ed8577b22cbfea)

Please commit changes to branch `2021_release`

Do you have an idea of what could be happening? @wvangeit @mgeplf

**Comment by wvangeit** [comment]
so just to be sure, you're getting this because you updating all libraries to the latest versions?

**Comment by antonelepfl** [comment]
Indeed and also we have moved away from Collab to use NOTO

**Comment by wvangeit** [comment]
I upgraded numpy in the notebook (!pip install numpy --upgrade) and that solved the issue it seems. Not sure if that's a good idea to do in the final notebook. But so it seems there is an issue with numpy.

**Comment by antonelepfl** [comment]
With the latest version of Numpy, the issue does not appear anymore.

![Screenshot 2021-07-09 at 10 30 01](https://user-images.githubusercontent.com/24406041/125048870-a60a1580-e0a0-11eb-9c65-229ad17ebf2a.png)

So I think we can remove the banner

![Screenshot 2021-07-09 at 10 28 26](https://user-images.githubusercontent.com/24406041/125048798-95599f80-e0a0-11eb-9bd5-f5d4a626b39b.png)


FYI @alex4200

**Comment by alex4200** [comment]
Yes, I had a quick look, I can confirm the error does not appear anymore.
