### ISSUE TITLE
Not a zipfile?

### ISSUE THREAD

**Issue by alobiz-a** [BlueBrain/MOOC-neurons-and-synapses-2017#85]
Dear staff,

I have put a lot of effort into learning all the content for this course and I have done everything but the final graded exercise but now I am having some issues with the collab. First of all, I wasn't able to initalise the collab because of changes to the platform. I asked about this on Github and was directed to the jupyter notebook for week 6, which I was told to download to my device. When using this, I encountered some errors and queried again and got told that some of the features wouldn't work well on a Windows computer, and that it was advised to do them on the platform. This put me back where I started. Now, I am really desperate to finish this before the course is archived as I have worked super hard since December 2020 on getting through all the contents and want to be able to obtain the certificate for this course. All I need is to finish the Final Graded Assignment but how can I do that if it doesn't work well on my device? Desperate, as I know this will be shut down tomorrow, I scrolled through all the collabs and found an empty week 6 one, which I copied onto one of my other collabs. I have worked through this but have not been able to get far as I encountered this error (see snip):
![image](https://user-images.githubusercontent.com/76615392/132415080-1c8295d5-d240-4dbb-9bb4-63ced1ce6be4.png)

Please help me. This course has been amazing and it would be painful not to finish it nor get recognition for all the work I've put in over these past months.

Best wishes,

Ari

**Comment by jdcourcol** [comment]
It seems similar to : https://github.com/BlueBrain/MOOC-neurons-and-synapses-2017/issues/61
where a fix has been delivered here: https://github.com/BlueBrain/MOOC-neurons-and-synapses-2017/pull/63/files

Would that solve your issue ?

**Comment by jdcourcol** [comment]
Hello, without any feedback, I will close this issue next week.

**Comment by jdcourcol** [comment]
no update from user. closing.
