### ISSUE TITLE
One_cell_minds: ModuleNotFoundError

### ISSUE THREAD

**Issue by martasaccher** [BlueBrain/MOOC-neurons-and-synapses-2017#91]
I am trying to run the notebook one-cell_minds on binder ut I keep getting a Module not found error. I think there is some problem with the dependencies. Could you maybe help me?

![issue](https://user-images.githubusercontent.com/80199675/141343323-5c22b30e-d2a7-44a2-b414-d0f862599c6c.png)

Thank you in advance!

Marta

**Comment by jdcourcol** [comment]
@MFSY can you look into that ?

**Comment by PhaedraKS** [comment]
Hello, I am having this exact same problem.

**Comment by stefanoantonel** [comment]
@MFSY any news on this?

**Comment by MFSY** [comment]
Hi @stefanoantonel @PhaedraKS ,

Looking into this.

**Comment by MFSY** [comment]
It should be fixed now. @PhaedraKS can you try again with the new version of the notebook and let us know if the error is fixed ?

**Comment by PhaedraKS** [comment]
Thank you! That error is now fixed and that part of the tutorial now works 👍
