### ISSUE TITLE
week 2 grade assignment issue

### ISSUE THREAD

**Issue by jdcourcol** [BlueBrain/MOOC-neurons-and-synapses-2017#95]
https://support.humanbrainproject.eu/#ticket/zoom/8393

![image](https://user-images.githubusercontent.com/5441880/154276074-696831ef-3f08-4c6e-ab07-7ec9bef17713.png)

**Comment by jdcourcol** [comment]
@samuel-kerrien  another issue with week 2.

**Comment by samuel-kerrien** [comment]
Dear user,

Thanks a lot for reporting your issue.

A new version of the edX MOOC has been released in September 2021 and it appears we have not appropriately updated the content in the HBP platform. The Simulation Neuroscience MOOC / Week 2, including its tutorial, is entirely documented in the edX platform. The current content of Week 2 in edX has a hands on tutorial but does not have a graded assignment anymore, it also features multiple quizzes.

I am not able to log into the HBP platform at the moment so I will enquire toward HBP and attempt to update the pages that related to the MOOC week 2 to make that clear.

I really apologies for the confusion this created and I hope you didn't lose too much time over it.
I will provide an update when the relevant HBP pages have been updated.

Best regards
Samuel

**Comment by alex4200** [comment]
Issue solved by user
