### ISSUE TITLE
Week 2 tutorial: Integrate Neuroscience Datasets from Multiple Sources using MINDS

### ISSUE THREAD

**Issue by PhaedraKS** [BlueBrain/MOOC-neurons-and-synapses-2017#96]
Hello,
I just had this same issue but with another part of the tutorial.
I hope this issue can be fixed in a similar way.

Tutorial: Integrate Neuroscience Datasets from Multiple Sources using MINDS
Configure a forge client to store, manage and access datasets
error:
/srv/conda/envs/notebook/lib/python3.7/site-packages/rdflib_jsonld/__init__.py:12: DeprecationWarning: The rdflib-jsonld package has been integrated into rdflib as of rdflib==6.0.1.  Please remove rdflib-jsonld from your project's dependencies.
  DeprecationWarning,

Thank you for any help and your time,
Phaedra

**Comment by jdcourcol** [comment]
@MFSY I am assigning that to you as it is week 2.

**Comment by MFSY** [comment]
It should be fixed now. @PhaedraKS please try again and let us know if any error subsist.

**Comment by PhaedraKS** [comment]
The error is fixed, thank you. 
I also have a different error now 

dataset_from_different_sources
select metadata
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_61/1646912356.py in <module>
     32                                             __typename\n  }\n}\n"""
     33                                })
---> 34 nm_mouselight_graphql = json.loads(nm_request.text)["data"]["searchNeurons"]["neurons"]
     35 nm_mouselight_names = [x["idString"] for x in nm_mouselight_graphql]

KeyError: 'data'

**Comment by MFSY** [comment]
Hi @PhaedraKS ,

Mouselight changed their API => hence the error. The error should be fixed now.

**Comment by MFSY** [comment]
Closing this issue see #97
