### ISSUE TITLE
Week 2 Tutorial

### ISSUE THREAD

**Issue by PhaedraKS** [BlueBrain/MOOC-neurons-and-synapses-2017#97]
Hello,
I have this error now:

dataset_from_different_sources
select metadata

KeyError Traceback (most recent call last)
/tmp/ipykernel_61/1646912356.py in
32 __typename\n }\n}\n"""
33 })
---> 34 nm_mouselight_graphql = json.loads(nm_request.text)["data"]["searchNeurons"]["neurons"]
35 nm_mouselight_names = [x["idString"] for x in nm_mouselight_graphql]

KeyError: 'data'

**Comment by MFSY** [comment]
Hi @PhaedraKS ,

Mouselight changed their API => hence the error. The error should be fixed now.

**Comment by PhaedraKS** [comment]
Yes very good,
it has worked and I have data in Sandbox.
Thank you!

**Comment by MFSY** [comment]
Happy to help @PhaedraKS

**Comment by jdcourcol** [comment]
don't forget to close @MFSY

**Comment by MFSY** [comment]
Hi @jdcourcol ,

Thanks for closing. I do not have the necessary rights to close an issue in this repo.

**Comment by jdcourcol** [comment]
sorry about that, I granted you permission.

**Comment by MFSY** [comment]
Thanks @jdcourcol
